import json,subprocess
from pathlib import Path
A='174d74e1-3fdf-41fd-99ed-047612b2963f'
P=Path('reports/GEDE01')/A
E=Path('reports/GEDE01/objdiff-'+A+'.json')
d=json.loads(E.read_text())
for label,cmd in [('configure-final',['python3','configure.py']),('build-final',['.tools/bin/ninja','-j2']),('dol-sha1',['sha1sum','build/GEDE01/main.dol'])]:
 r=subprocess.run(cmd,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
 (P/(label+'.log')).write_text(r.stdout)
 d['runs'].append({'label':label,'command':cmd,'cwd':'eternal-darkness-decomp','returncode':r.returncode,'output':r.stdout})
 assert r.returncode==0
 if label=='dol-sha1':assert r.stdout.split()[0]=='ea24b6af954876ce072562ff39cdb4c81d32be1f'
d['full_build']={'command':['.tools/bin/ninja','-j2'],'returncode':0,'raw_output':'eternal-darkness-decomp/'+str(P/'build-full.log'),'note':'First full build recompiled 905 build steps; subsequent final verification was successful.'}
d['dol']={'expected_sha1':'ea24b6af954876ce072562ff39cdb4c81d32be1f','actual_sha1':r.stdout.split()[0],'verified':True,'scope':'Retail-linked DOL: this NonMatching source is built for comparison but not linked.'}
div='Canonical and relocation-strict (function_reloc_diffs=name_address) objdiff both measure 95.87273%, with 220 retail and 220 generated bytes. All eight ELF relocation offsets, types, targets and addends agree. At 0xA0/0xA4/0xA8 retail computes manager_count, entries, then entry_count; generated code computes entry_count, manager_count, then entries. At 0xC8/0xCC retail loads r28 then saved LR, while generated code loads saved LR then r28. Equivalent byte-stride, signed-stride, integer-address, reverse-byte-add, count-operand-commutation, signed-count-addition, and typed-manager-increment variants remain 95.87273%; explicit shift-and-add stride regresses to 86.23637%. Retained the unchanged best honest NonMatching reconstruction. Full canonical build and expected DOL SHA-1 pass.'
d['divergence']=div
E.write_text(json.dumps(d,indent=2)+'\n')
envelope={'version':1,'assignment_id':A,'attempt':6,'base_commit':'befaf049887fca4c9871d2a3af7deb3051cebed0','target':'fn_8017CCD8','status':'attempted','evidence':['eternal-darkness-decomp/'+str(E)],'divergence':div}
Path('reports/GEDE01/durable-'+A+'.json').write_text(json.dumps(envelope,indent=2)+'\n')
print(r.stdout.strip())
